import Head from 'next/head';
import Sidebar from '../components/Sidebar';
import Feed from '../components/Feed';
import Widgets from '../components/Widgets';
import { NewsResultsTypes, RandomUserResultTypes } from '../types/types';
import CommentModal from '../components/CommentModal';

type IndexPropTypes = {
  newsResults: NewsResultsTypes;
  randomUsersResults: RandomUserResultTypes;
};

export default function Home({
  newsResults,
  randomUsersResults
}: IndexPropTypes) {
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen mx-auto">
        <Sidebar />
        <Feed />
        <Widgets
          newsResults={newsResults.articles}
          randomUsers={randomUsersResults.results}
        />
        <CommentModal />
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch(
    'https://saurav.tech/NewsAPI/top-headlines/category/business/us.json'
  );
  const newsResults: NewsResultsTypes = await res.json();

  if (newsResults!) {
    console.error(
      `There was an issue finding new results for tech - ${newsResults}`
    );
  }

  let randomUsersResults: RandomUserResultTypes = { results: [] };

  try {
    const res = await fetch(
      'https://randomuser.me/api/?results=30&inc=name,login,picture'
    );

    randomUsersResults = await res.json();
  } catch (e) {
    randomUsersResults = { results: [] };
  }
  return {
    props: {
      newsResults,
      randomUsersResults
    }
  };
};
